[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 100_000
seed = "0x01010"

[fuzz]
runs = 10_000

[fmt]
ignore = ["test/MedianOracleReference.sol"]

[invariant]
runs = 1000
depth = 5

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
